export const USER_POST = "USER_POST";
export const USER_POST_DATA = "USER_POST_DATA";
export const USER_POST_LIST = "USER_POST_LIST";
export const USER_POST_COMMENT_DATA = "USER_POST_COMMENT_DATA";
export const USER_POST_COMMENT_LIST = "USER_POST_COMMENT_LIST";
export const USER_POST_FAIL = "USER_POST_FAIL";